### ISSUE TITLE
Specify parsing error handling

### ISSUE THREAD

**Issue by hiroshige-g** [WICG/import-maps#100]
- What happens if, for example,
    - JSON parsing fails
    - There is no "imports" entry
    - The key or value is an Invalid URL
    - The value is not a string or list (e.g. is an integer)
- Which kind of validation is done at parsing time and which at mapping time?
    - An invalid URL causes a parsing error, or is skipped at mapping time, or something else?

The reference implementation is mostly permissive about errors in values (ignore invalid entries rather than erroring the entire map).

I think the priority is low and not an implementation blocker. Filing this for tracking and explicit decision.

**Comment by domenic** [comment]
The reference implementation should be pretty up to date on this. See also #80 for previous discussion.

In general I've tried to do as much validation as possible up-front, at parsing time. But, I don't think the difference will be observable.

**Comment by hiroshige-g** [comment]
Oh, thanks! (I'm not sure why I couldn't catch that thread when I searched)
