### ISSUE TITLE
proposal: import(url, config) and module realms

### ISSUE THREAD

**Issue by mariusGundersen** [WICG/import-maps#103]
I'm not sure if this is the right place or if this has been proposed before other places, but I think there is an opportunity to solve many problems at the same time, including import maps, by adding a second (optional) parameter(ish thing) to the dynamic import statement. I realize that the import statement isn't a function call, not really, so maybe calling it a parameter is wrong. The use of it would then look something like this:

```js
let main = await import('./main.js', {
  map: {/* specify the import map here */},
  // many potential things here
});
```

The config object would be an object that can contain several different properties including import-maps and other ideas like methods for resolving, fetching and transpiling modules. It would be easy to add more features here in the future.

The main thing though is that this would overlap with the [realms proposal](https://github.com/tc39/proposal-realms) in that all the transitively imported modules would exist in their own context. This context would be separate from any other context, including the global context, and would have its own module instances. So if you call the code above twice you would create two contexts and there would exists two module intsances of main, which would have their own state. 

There are several reasons why I propose this:

It is a way to create immutability, which I think would be easier to implement and understand. Since the map has to be created before the first import, there is no way to change the current import rules. And since the map is handed off to the import() call (is it a call? Probably not really) there is no way to change the map or the rules afterwards. This means that there is no issues with how the rules for importing a module changes after it has been imported.

The maps can be generated dynamically, or even imported from another module. They are not static and don't have to be specified in special script tags. You could use JavaScript to build up the map object, looping through lists and interpolating strings, if you want to. 

By having contexts (or realms) you can sandbox code easily. For example, you could use it for unit testing by running each test in a separate context, in parallel, and know that no matter what the code does it cannot affect another test running in another context. And you could mock some of the dependencies of the module being tested using maps. 

There are several other things the config object could include, like:

The rules from the realm proposal, or an instance of a Realm. This way you can either create a completely isolated and sandboxed context that has its own window object and global variables, or you could have several contexts that share global variables. You could also change out global variables, like window or the DOM, if you need to.

A way to inject an existing module into the context. This would be useful for sharing a module instance between several contexts, for example one that can store global state. It could work something like this:

```js
import * as state from './state.js';

let main = await import('./main.js', {
  modules: {
    'state': state
  }
});

main.putSomethingInState();
state.get('something');
```

Ok, so this might be a lot of vague ideas and not a very formal proposal, so I realize it's not going to be accepted directly. The ideas here are based on having this available through AMD modules years ago and the frustration of not having anything like this today in ES6 modules.

**Comment by domenic** [comment]
Thanks for the interest. This is not really related to import maps, and so this is not the forum where to best propose it, so I'll close the issue.

But, I'll let you know that I did propose a related idea to TC39 about two years ago, and they shot it down by preferring out-of-band metadata, instead of modifications to `import` statements and `import()` expressions. You can see [the presentation](https://docs.google.com/presentation/d/1qfoLTniLUVJ5YNFrha7BaVumAnW0ZgcCfUU8UbyyuYY/edit) and the [minutes of the discussion](https://github.com/tc39/tc39-notes/blob/master/es8/2017-05/may-23.md#16iib-module-import-options-discussion-potentially-for-stage-1).

**Comment by jespertheend** [comment]
Shoot, I really need this. Specifically for the unit test use case described above. I was hoping to stub some modules this way.
Has anything changed since your last post @domenic? What makes this request less related to import maps than, say, import maps for Workers?
