### ISSUE TITLE
Can we publish reference implementation to NPM

### ISSUE THREAD

**Issue by usergenic** [WICG/import-maps#121]
I'm working on a koa middleware to perform on-demand rewrites of specifiers based on import map and would love to not copy-pasta the parser and resolver into my codebase.

🙏

**Comment by domenic** [comment]
Hey! I'm glad you're so enthused; however, I'm sorry to say I can't commit to publishing, revving, and supporting an npm package. The reference implementation in this repository is purely to serve the purpose of writing the spec and fleshing out behavior, and I can't take on the additional burden of making it a software project people might depend on for writing their own libraries. That comes with additional requirements, both on my time and on the code, which are not tenable for me.

You're very welcome to take the code, and publish your own package. We've seen people do this with other reference implementations, e.g. the Streams Standard reference implementation at https://github.com/whatwg/streams/tree/master/reference-implementation does not get published to npm by the standard editors, but a community member maintains a separate [web streams polyfill](https://github.com/MattiasBuelens/web-streams-polyfill/). The polyfill is derived from the reference implementation but takes on all the hard tasks like producing transpiled variants, picking which tests it is OK to fail, adding TypeScript definitions, etc.

Hope this helps!

**Comment by usergenic** [comment]
I had assumed from the 1.0.0-pre version in package.json that this was in a pre-release state and a release was forthcoming.  I didn't want to duplicate any efforts, but I'll go ahead and pursue publishing a derivative work then.

Thanks for the reply and the explanation @domenic :)
Cheers!

**Comment by daKmoR** [comment]
@usergenic, in the end, did something got published somewhere? 🤗
