### ISSUE TITLE
Supporting scope-relative resolution

### ISSUE THREAD

**Issue by guybedford** [WICG/import-maps#122]
It could be useful to support a syntax for scope-relative resolution like `import "~/sub/path.js"`, where "~" means relative to the matching scope of the current module.

This helps with the common problem of backtracking in packages - where you always need to backtrack to up the package folders to load a module from another folder in the same package.

In the Node.js modules group, we've been considering this proposal - https://github.com/guybedford/package-name-resolution, which allows the package.json "name" to be a package self-reference, allowing usage like `import "pkg/sub/path.js"` instead of `import "../../sub/path.js"`.

One suggestion was to make this syntactical instead of using the package.json "name", using `~` as described above.

Would there be interest in such a feature here?

**Comment by justinfagnani** [comment]
I think using the package name is rather nice actually. Especially compared to adding another symbol to the path syntax.

**Comment by guybedford** [comment]
@ljharb was expressing concerns over using the package.json "name" due to the inability for us to support this in CommonJS, so we were considering if a syntax option might be better.

**Comment by domenic** [comment]
I don't really understand the Node.js and package.json connection, but reifying scopes in this way seems like a novel concept that I'm wary of. I'd rather scopes be transparent and not visible to the module; they're a way for the application developer to control resolution, and should not serve a dual purpose as being some sort of package-root.

For example, a nice property of the current design is module A can be under a scope and that doesn't change module A's behavior directly. It's only by changing the resolution of module B inside the scope, that the behavior of module A might change, iff A references B.

If there's a desire to create a notion of "package-root" in this way, that varies across the app, I'd suggest applications just create scoped resolutions for the `~` package.

**Comment by guybedford** [comment]
It helps to hear feedback on the import maps side to understand if this could work more closely with import maps or should remain an explicit mapping.

It sounds like the explicit mapping approach is the sensible path forward indeed for these cases.
