### ISSUE TITLE
Proposal: package hashes

### ISSUE THREAD

**Issue by troglotit** [WICG/import-maps#123]
# Overview
Hey! I wanted to write similar proposal, but with larger scope: to introduce hashsums to packages:
```json
{
  "algo": "SHA-256",
  "imports": {
	"react": {
	  "url": "/packages/react.js",
	  "hash": "1be00341082e25c4e251ca6713e767f7131a2823b0052caf9c9b006ec512f6cb"
	},
	"lodash": {
	  "url": "/packages/lodash.js",
	  "hash": "3fdba35f04dc8c462986c992bcf875546257113072a909c162f7e470e581e278"
	}
  }
}
```
# Motivation 
- Easy caching for browsers, no need to download the same file if a package with particular file has same hash.
- Reuse of cached packages between websites!
- Ability for browsers to make advanced analytics and optimization like "70% of websites use this lodash version, we are going to preload lodash in the memory just in case for all websites, maybe write C++ implementation for performance. TC39 needs to have a look of bringing it into std library".

Is it too much for this particular proposal and better to make a different proposal?

**Comment by troglotit** [comment]
I'm reading https://github.com/WICG/import-maps#adjacent-concepts, and seems like it was thought out before. Closing before having more promising thoughts.

**Comment by troglotit** [comment]
Yeah, my proposal has quite a few conflicts with import maps, for example, scopes, my proposal focusing more into "one file per package". 

I think "npm parity" is not worthy goal: bundlers are here to stay, they could rewrite dependencies of dependencies to top level import like "debug" -> "debug@2.4.3" or "debug@sha256:dsfdsfsf" or "bootstrap/bootstrap.css" or similar. Also, to produce import map in a modern webapp you'll need some compiler or bundlers anyway. 

I'd be glad to hear your thoughts, but feel free to close even without any comments. Thanks!

**Comment by domenic** [comment]
This makes sense as a different proposal to me :)
