### ISSUE TITLE
Strategy for working with Symbols()

### ISSUE THREAD

**Issue by bahrus** [WICG/import-maps#132]
This issue may be more a reflection of my own muddled thinking than anything.  I just want to make sure there isn't something here that requires adjusting in the import maps proposal.  If no adjustments needed, feel free to close.

I recently experimented with using ES6 symbols for some of my mixin methods.  The idea being that  doing so would guarantee they wouldn't clash with other mixins.  I'm thinking maybe what I'm really looking for is using the private keyword, but I don't see how that would solve the problem if you combine multiple mixins with the same private method name.  So assuming symbols is the right solution...

The problem I kept running into was from using npm combined with Polymer's bare import specifier emulation -- If all my npm packages that used the symbols were completely up to date, everything worked.

But the moment any one of them was behind, I would end up with local copies of the dependencies, and the symbols wouldn't match, resulting in run time errors.

I ended up backing out of using symbols because it was more trouble than it was worth.

It seems like if you use symbols that you want to share cross package, you need to be able to specify a "singleton" somehow, to guarantee everyone uses the same version.

If no bundling is used, I *think* import maps *could* guarantee that any reference to an ES6 symbol all point to the same path, with enough care, but I could also see similar scenarios arising when you start talking about scoped packages.  And then I think about using something like PikaWeb, which bundles each component, and in the process bundles local copies of the symbol.  I'm just not seeing how that would work.

**Comment by ljharb** [comment]
That seems like a usecase for Symbol.for, not something import maps has to address?

**Comment by bahrus** [comment]
That's a good suggestion, I was thinking about that.  But if a common string were used inside Symbol.for(), wouldn't we have clashes again?  So I was thinking maybe the right solution is to use Symbol.for, with a string guid as the key, and then stash the symbols into an object with easier names inside that object.  But it felt like I was just winging it (in my head, never actually tried it).  Like is that really any easier than just using guid's.?  Is it accomplishing anything, really?

**Comment by ljharb** [comment]
This also sounds like the use case for peerDependencies - whatever package has the symbols needs to be a singleton, and a peer dep of everything else.

We’re getting off topic tho, so I’ll leave the thread for someone to answer re import maps specifically :-)

**Comment by domenic** [comment]
I can't really think of how this is related to import maps, personally.

**Comment by bahrus** [comment]
That's fine, I will close with a clear conscience then.  :-).  Thanks.

**Comment by guybedford** [comment]
While not directly related to this proposal, how builds work under import maps exactly does come down to questions of instances in terms of handling versioning and builds.

On the one side of the scale, every package builds all its dependencies (as all Node.js-only packages really should for performance, see https://github.com/zeit/ncc).

On the other side of the scale, we have every dependency loaded as separate files kind of like the npm ecosystem exists today.

It is clear that the best performance for the browser lies somewhere in the middle - sharing large package dependencies, while inlining small, pure, package dependencies, where duplication is not so much a concern.

Every user will need to individually determine which side of the scale each dependency they add to their browser library lands - is it small enough to inline, or is it large enough that it should be shared. Think of it as a devDependencies v dependencies question.

Instancing problems like symbols as mentioned here exactly do cause the line to fall towards shared dependencies over inlined devDependencies so this is exactly the kind of thinking we should all get used to for post-import-map JavaScript.
