### ISSUE TITLE
Behavior changes in specifier resolution without import maps

### ISSUE THREAD

**Issue by hiroshige-g** [WICG/import-maps#141]
#resolve-a-module-specifier fails for non-fetch scheme URLs because of the check at Step 4 of #parse-a-url-like-import-specifier, while previously #resolve-a-module-specifier itself succeeded (subsequent fetch would still fail though).
This slightly affects the behavior of pages even without import maps.

For example,

```
<script type="module">
import './fetch-failure.mjs'; // The fetch will fail.
import 'nonfetchscheme:foobar';
</script>
```

The current HTML spec, all the specifier resolution are successful, and two fetches to `fetch-failure.mjs` and `nonfetchscheme:foobar` are made and failed.
Fetch failure of `fetch-failure.mjs` is reported to error console.

In the current import map spec, the specifier resolution of `nonfetchscheme:foobar` fails, and thus creating the top-level inline module script also fails. In this case, no network request to `fetch-failure.mjs` is sent to the server, and creation error of the inline script is reported to error console.

I don't expect this change is important, as I don't expect stable prodution systems contain such non-fetch scheme URLs and errors.
Probably it's better to first land a HTML spec change to make this behavior change (that can be done independently from import maps), and then land import map changes (without behavior changes to non-import-map cases).

**Comment by guybedford** [comment]
This seems to me like a data point indicating how fetch scheme resolver errors lead to unexpected results. I'm still not sure I see what benefit fetch scheme filtering restrictions give to incur these types of behavior changes.

**Comment by domenic** [comment]
This seems like a great improvement in the current spec, in that it catches errors earlier before any side effects can occur. This is a good change.

I agree we could first land a HTML spec change with tests for this minor improvement and then base import maps on top of it. @hiroshige-g can you take that on?

**Comment by domenic** [comment]
As I mentioned in #158, now that we no longer treat the `std:` scheme as special, I'm more inclined to just remove all special-casing of schemes (letting them only fail at fetch time).
