### ISSUE TITLE
How do we install package name maps? Node.js context

### ISSUE THREAD

**Issue by caub** [WICG/import-maps#15]
Does Node.js need additional configuration? can it be in `package.json`?

If I understand well, this proposal may cover webpack's custom resolvers and aliases? and the possibility to have internal import 'bindings' like:

I've often things like
```js
	resolve: {
		extensions: ['.js', '.json'],
		modules: ['src', 'node_modules'],
		alias: {
			assets: `${__dirname}/assets/`,
		},
	},
```
that would benefit being standardized. Since it's needed by test engines and linters also

**Comment by matthewp** [comment]
This proposal doesn't (currently at least) cover automatic extensions or searching for modules in multiple directories. Node might want to extend this proposal with their own custom properties, but I hope they don't! cc @bmeck for his thoughts here.

**Comment by bmeck** [comment]
Given that we have loader hooks I would probably suggest we leave this up to a userland loader for some time.

cc: @nodejs/modules

**Comment by justinfagnani** [comment]
> This proposal doesn't (currently at least) cover automatic extensions or searching for modules in multiple directories

I don't think the proposal will ever cover searching, that's something we need to actively avoid.

**Comment by domenic** [comment]
Let me close this, as the spec won't be the one deciding this, but instead the Node.js team. Perhaps @guybedford or @MylesBorins know the right place to direct @caub to see where any ongoing discussions are happening?
