### ISSUE TITLE
Centralize and simplify checks on URLs/specifiers

### ISSUE THREAD

**Issue by domenic** [WICG/import-maps#158]
As originally mentioned by @hiroshige-g in https://github.com/WICG/import-maps/pull/152#issuecomment-510681264, we have a number of different checks (especially after #152): during parsing, resolving, and fetching. They are not all identical. We should try to centralize and simplify them.

@hiroshige-g has a table in [this chromium.org document](https://docs.google.com/document/d/1m4wSpE0KyioTHtYK927RQoaANB_v1gRfyD1jitxmO7s/edit#) (unfortunately not public) where he has made a matrix of the differences.

**Comment by hiroshige-g** [comment]
FYI I made the doc public.

**Comment by domenic** [comment]
With the removal of built-in module support in #176 this becomes much simpler.

Since we no longer need to treat any schemes as special, perhaps we should just remove the fetch scheme check entirely, and then everything will be uniform. Thoughts appreciated.

**Comment by bakkot** [comment]
> perhaps we should just remove the fetch scheme check entirely, and then everything will be uniform

Personally I'm in favor of this. It would make the error more uniform, so that having `import('wss:foo')` would give the same error as having `import('foo')` with an import map of `{ "imports": { "foo": "wss:foo" } }`.

**Comment by domenic** [comment]
I think checks are pretty centralized and simple now. @hiroshige-g do you agree?

**Comment by hiroshige-g** [comment]
Agree. Closing.
