### ISSUE TITLE
Consider dual support for std: and @std/

### ISSUE THREAD

**Issue by hiroshige-g** [WICG/import-maps#162]
As https://github.com/tc39/proposal-javascript-standard-library/issues/12 is still open, it would be helpful to consider how to support `@std/` specifiers in the spec.

Once the issue is resolved, then we can either

- Drop `@std/` support added in this issue, or
- Drop `std:` support (perhaps switching to `import:` URLs, or simply making `std:` URLs internal in the spec/implementation and not exposing to users),

depending on the conclusion there.

**Comment by domenic** [comment]
Oh, sorry, I think you misinterpreted what I meant in our meeting. There is nobody in the standards space considering `@std/` at this point, just different URL schemes (like `lib:`).

Ultimately I think we should not treat this as a spec issue (or an MVP issue), and instead just a potential compat issue for Chrome if the import maps spec needs to change from `std:` to `lib:` or similar in the future.

**Comment by ljharb** [comment]
I don't think that's accurate; TC39 hasn't yet ruled out namespaces, nor has node.

**Comment by domenic** [comment]
I think we have different interpretations of different conversations. For the import maps spec purpose, I am content saying we do not need to complicate the specification with support for `@std/`.

**Comment by ljharb** [comment]
I was responding to "There is nobody in the standards space", which is inaccurate; I think you're making the right choice by not complicating import maps at this time.
