### ISSUE TITLE
Question: any idea when it might become enabled by default in chrome?

### ISSUE THREAD

**Issue by daKmoR** [WICG/import-maps#175]
import-maps have been pretty nice so far for us 🤗 

any rough idea when it will become enabled by default in chrome? I wanna be prepared and celebrate 😬

**Comment by ljharb** [comment]
I’d hope not before other browsers have concrete plans to ship it. Do they?

**Comment by domenic** [comment]
(We don't hold back shipping things in Chrome in the way @ljharb implies.)

We're working on enabling by default as soon as we can get our implementation updated for the latest spec changes; watch blink-dev for announcements!

I'll close this issue since it's not really related to the spec.
