### ISSUE TITLE
Remove fetch scheme checks from scopes?

### ISSUE THREAD

**Issue by domenic** [WICG/import-maps#188]
#180 removed the fetch scheme check for specifiers. Should we also remove it for scope prefixes? That is the only remaining check for fetch schemes in the spec.

I think we probably should, just to keep things simple.

Somewhat part of #158.

**Comment by hiroshige-g** [comment]
> I think we probably should, just to keep things simple.

Probably, for simplicity. I'll draft a PR.

(I also noticed I forgot to implement this check, so current ToT chromium doesn't check fetch scheme at all)
