### ISSUE TITLE
Clarification of RHS bare specifiers in reduced implementation

### ISSUE THREAD

**Issue by guybedford** [WICG/import-maps#192]
I was just looking at the spec and tests for the case of RHS bare specifiers like:

```json
{
  "imports": {
    "foo": "foo.js"
  }
}
```

As far as I can tell from the spec and implementation `import 'foo'` with the above is an error right? And this is to leave the door open for cascading implementations?

Seems a useful thing to clearly document as some users may find this confusing.

**Comment by domenic** [comment]
Well, it's a parse-time error in https://wicg.github.io/import-maps/#parse-a-url-like-import-specifier, not an `import`-time error. But yes, that's the current idea.

+1 on documenting.
