### ISSUE TITLE
Seemingly incorrect use of must

### ISSUE THREAD

**Issue by annevk** [WICG/import-maps#193]
https://wicg.github.io/import-maps/#parse-an-import-map-string contains usage of must that are not requirements on implementers but on developers. However, they would be better suited as requirements in a "writing import maps" section.

**Comment by domenic** [comment]
I think it's OK for suggested error messages to use "must". (You didn't quote any examples, but I think that's what you're referring to?)

**Comment by annevk** [comment]
Yeah, I think that's confusing, very similar to how we avoid must in notes.
