### ISSUE TITLE
Can specifiers be relative schemes ?

### ISSUE THREAD

**Issue by nestarz** [WICG/import-maps#215]
I would like to map some calls to files that have the relative scheme `./src/...` to `./dist/...`
Can I do this using import-maps ? 
Can it be something like this:
```
{
    "imports": {
        "./src/foo.js": "./dist/foo.js",
    }
}
```
And as broader question, can specifiers be any string ?

Thanks

**Comment by jkrems** [comment]
I think this is mentioned in one of the README examples (https://github.com/WICG/import-maps#general-url-like-specifier-remapping). Afaik URL-like keys will be normalized to full URLs. The following should be equivalent (assuming inline source maps on a page with the base URL `https://x.example/app/`):

```js
{
    "imports": {
        "./src/foo.js": "./dist/foo.js",
    }
}

{
    "imports": {
        "https://x.example/app/src/foo.js": "./dist/foo.js",
    }
}

{
    "imports": {
        "/app/src/foo.js": "./dist/foo.js",
    }
}

{
    "imports": {
        "https://x.example/app/src/foo.js": "https://x.example/app/dist/foo.js",
    }
}
```
