### ISSUE TITLE
Document privacy expectations vs prefetching

### ISSUE THREAD

**Issue by moztcampbell** [WICG/import-maps#219]
Related to #218..

With described use-case of CDN-remapping, I would expect some developers to use this to avoid their traffic going to specific CDNs. With the dynamic import-map tag insertion, it is very conceivable that a browser will be eagerly prefetching module graphs before the import-map is executed.

Can we clarify in https://github.com/WICG/import-maps#general-url-like-specifier-remapping if browser may still make fetches against the original URI before the import-map is loaded and the requests are re-issued?

**Comment by domenic** [comment]
> it is very conceivable that a browser will be eagerly prefetching module graphs before the import-map is executed.

I'm really not sure where you're getting this from. Can you point me to what part of the spec leads you to believe this?

> Can we clarify in https://github.com/WICG/import-maps#general-url-like-specifier-remapping if browser may still make fetches against the original URI before the import-map is loaded and the requests are re-issued?

This is not true in either the current HTML Standard nor after it is modified by import maps.

To cause prefetches, you need to use `<link rel="preload" href="a URL">`.

**Comment by moztcampbell** [comment]
I'm definitely misinterpreting things here. Closing issue.
