### ISSUE TITLE
how are direct and indirect "absolute cross origin urls" modules resolved?

### ISSUE THREAD

**Issue by serapath** [WICG/import-maps#236]
I skimmed the spec and read through this repo and it's issues, but still - there seem to be so many details involved that i couldn't figure it out easily. I appreciate all the ideas about `"depcache"` which to me sounds like `package-lock.json` or `npm shrinkwrap` so you can snapshot the entire dependency tree to not only freeze versions, but also to make lookup easier. The issue though is, that if you want to just set up your website and require an external module that has many dependencies, you need tooling (something like `npm shrinkwrap`) to correctly generate the `importMap`.

---

It would be nice though if there was a solution (maybe slightly more inefficient than `"depcache"` - at least for the first load that could then cache and internally build up such a `"depcache"` file), that does **not** require tooling :-)

**A. what i was looking for but could not figure out:**
how are `"absolute-cross-origin-module-urls"` resolved?
1. `foo.com/index.html` loads `<script src="index.js"></script>` and has an `importMap`
2. `index.js` imports a bunch of modules:
   * => some with a local relative path which resolves just fine
   * => some with absolut identifier like e.g. `import("lodash")` which is specified in the `importMap`
      * to either another local javascript module
      * to an absolute same origin javascript module
      * to an **`"absolute-cross-origin-module-urls"`**
   * => some with absolute same origin urls, e.g. `foo.com/foo.js`
   * => some with **`"absolute-cross-origin-module-urls"`**, e.g. `bar.com/bar.js`

**B. what i imagine the solution looks like, but maybe somebody can point me to how it is actually solved:**
1. all imports which need to reference directly or indirectly via local importmap a **absolute-cross-origin-url** need to point to a `manifest.json`, which defines at least:
    1. a `main script`, which is the file that is actually imported via the original import statement
    2. a `importMap` field, which specifies an import map or the exact link to an importMap to look up all scripts imported directly or indirectly via `main script` - until it hits again an **absolute-cross-origin-url** where this whole procedure repeats

**Comment by domenic** [comment]
There is no difference between same-origin and cross-origin URLs in terms of how they are treated by an import map.

I'll close this, since I think the readme already covers this in the https://github.com/WICG/import-maps#general-url-like-specifier-remapping example, but I'm happy to reopen and continue discussing if I misunderstood!

**Comment by serapath** [comment]
Thx, @domenic 
I think this is a misunderstanding. As mentioned in the first parargraph, my understanding is, that **import maps** work somewhat similar in spirit to e.g. `package-lock.json` or `npm-shrinkwrap.json` and have to define all dependencies and the dependencies of dependencies, and so on. So, what I mean by "cross-origin" (full url) imports is, that if that imported script itself specifies local imports in its definition, how are they resolved?

**Comment by serapath** [comment]
I wish there was a way so a cross origin full url lookup for a script would allow that "remote script" to specify a file for its local dependencies, so I don't have to do that and I don't have to run tooling to generate my "import maps".

**Comment by domenic** [comment]
Can you provide a code example of the situation you're wondering about? E.g. give a series of URLs and their contents, and then ask a specific question where you're not sure what the current proposal does?

**Comment by serapath** [comment]
ok, let me try. maybe i got it all wrong - hopefully not :-)


Do I need to list `./baz.js` in my import map?
What if `baz.js` was a name instead that you would look up in an import map when resolving inside `./bar.js`?
  * would the `foo.com` import map have a way too use the import map from `bar.com` ?

---
https://foo.com/foo.js
```js
export const foo = "foo"
```
https://foo.com/index.html
```html
<!doctype html>
<html>
  <head><meta charset="utf-8"></head>
  <body><script type="module">
    import { foo } from "./foo.js"
    import { bar } from "https://bar.com/bar.js"

    console.log({ foo, bar })
  </script></body>
</html>
```
https://bar.com/bar.js
```js
import { baz } from "./baz.js"
export const bar = baz
```
https://bar.com/baz.js
```js
export const baz = "baz"
```

**Comment by domenic** [comment]
> Do I need to list ./baz.js in my import map?

No

> What if baz.js was a name instead that you would look up in an import map when resolving inside ./bar.js?

I don't really understand this question? Perhaps this needs a second code example?

> would the foo.com import map have a way too use the import map from bar.com ?

No. See https://github.com/WICG/import-maps#scope

**Comment by serapath** [comment]
# https://foo.com
https://foo.com/foo.js
```js
export const foo = "foo"
```

https://foo.com/index.html
```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <script type="importmap" src="./package.json"></script>
  </head>
  <body><script type="module">
    import { foo } from "foo"
    import { bar } from "bar"
    console.log({ foo, bar }) // { foo: "foo", bar:    ??????    }
  </script></body>
</html>
```

https://foo.com/package.json
```json
{
  "imports": {
    "foo": "./foo.js",
    "bar": "https://bar.com/bar.js"
  }
}
```

---

# https://bar.com
https://bar.com/bar.js
```js
import { baz } from "baz"
export const bar = baz
```
https://foo.com/index.html
```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <script type="importmap" src="./package.json"></script>
  </head>
  <body><script type="module">
    import { bar } from "bar"
    console.log({ bar })
  </script></body>
</html>
```
https://bar.com/package.json
```json
{
  "imports": {
    "bar": "./bar.js",
    "baz": "./baz.js", // <== this has the needed info
  }
}
```
https://bar.com/baz.js
```js
export const baz = "baz"
```

**Comment by serapath** [comment]
maybe the above is not a problem and already solved and just works, but i assume it currently doesn't work. So - could there be a hardcoded convention for an importmap name and location to solve scenarios like:
1. when a module is imported with a **full url** which has a different origin
2. and that "cross-origin-module" (e.g. `https://foo.com/foo.js` imports `https://bar.com/bar.js`)
3. and that "cross-origin-module" (e.g. `https://bar.com/bar.js` needs to lookup an import `"baz"`)

---
My favourite would be to be able to specify:

https://foo.com/package.json (the used "importmap")
```js
{
  "imports": {
    "foo": "./foo.js",
    "bar": "https://bar.com/package.json"
  }
}
``
so i can use:
https://foo.com/index.html
```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <script type="importmap" src="./package.json"></script>
  </head>
  <body><script type="module">
    import { foo } from "foo"
    import { bar } from "bar"
    console.log({ foo, bar }) // { foo: "foo", bar:    ??????    }
  </script></body>
</html>
```
which in turn knows how to use:
https://bar.com/package.json
```json
{
  "imports": {
    "bar": "./bar.js",
    "baz": "./baz.js",
  }
}
```

That way, the `"bar"` specifier used in the `"importmap"` on `"foo.com"` will use the `"https://bar.com/package.json"` to look up `"bar"` instead and from then on, resolve all imports that directly or indirectly happens in `"bar.js"` by using that sub-importmap

**Comment by domenic** [comment]
Yes, the above does not work as you're hoping. This is intentional, with the reasons why being covered in https://github.com/WICG/import-maps#scope.

**Comment by serapath** [comment]
I understand that reason, but everything could just work the way it works.
Only when you reference a json file in your import maps you explicitly opt into that mode.
it might be you in your personal project
it might be the CTO in your company
whoever it is - it is a conscious decision to decide its fast enough.
this could still be intercepted and cached by the service worker and it is all fine then.
...so why would anyone prevent the above feature given that?

I can't see any section in what you linked that would really rule out such an opt-in feature, unless the reasoning is stated in an open issue linked... haven't checked those.

could you give me a more specific hint or do you think as an opt-in feature this might be viable?

**Comment by domenic** [comment]
The idea is to ensure that there is a central place to control an application's module resolution. This is somewhat important from a security perspective, for example.

**Comment by serapath** [comment]
I understand that, but you have that under total control, because if you don't add:
```json
{
  "imports": {
    "foo": "./foo.js",
    "bar": "https://bar.com/package.json"
  }
}
```
a path to a `json` file, you do not delegate that from a security perspective, so you would only for example do it for other modules under your control or your companies control or vendors you trust and you can update your local import map to undo referencing a json file, so with the next deployed update, the browser will not any longer use the delegated importmap but requires the lookup to be included in your local importmap instead.

**benefits:**
hobby users and developers can develop quickly and try out things and when an app becomes something serious in production relied upon by many users, you just stop linking to delegated import maps but instead generate exhaustive local import maps to have full security control.

...basically not having it has no security upsides but huge development inconveniences and makes it almost un-usable without tooling, esepcially when you quickly want to prototype and change things is my feeling here.

**Comment by domenic** [comment]
I don't agree that delegating is a reasonable thing to do, sorry. I think you must be looking for a different proposal than this one. We're not going to add such functionality to import maps; they're one-per-application, assembled by build tools.

**Comment by serapath** [comment]
You say you do not agree and that it is not reasonable, but could you tell me why?
you mentioned security concerns, but if the `json` file is not referenced everything is secure, so projects can decide, so that concern is gone. why do you think it is unreasonable?

**Comment by domenic** [comment]
I'm sorry, it feels like I'm not really getting through no matter what I say, and I don't really have the time to repeat the same explanations. Maybe someone else watching the repository can help, but I need to disengage from this thread now, as to me it feels like it's going in circles.
