### ISSUE TITLE
Consider supporting trailing slash exact mappings

### ISSUE THREAD

**Issue by guybedford** [WICG/import-maps#257]
There is an old Node.js pattern whereby a `require('pkg/')` import style is permitted to resolve.

if trying to support such a map in import maps via:

```json
{
  "imports": {
    "pkg/": "/path/to/pkg/index.js"
  }
}
```

the browser console gives the error:

```
Ignored an import map value of "a/": Since specifierKey ended in a slash, so must the address: /a.js
```

If such a pattern were to remain used in Node.js ES modules, it might make sense to still consider supporting these cases resolving. //cc @hiroshige-g

**Comment by domenic** [comment]
Dupe of https://github.com/WICG/import-maps/issues/244 ?

**Comment by guybedford** [comment]
Ah thanks, yes closing. Wdyt re progress there? I'm tempted to consider proposing Node.js ban all trailing slash resolutions otherwise for ESM.

**Comment by domenic** [comment]
Yeah, I don't think we have any new information that would change the calculus over there...
