### ISSUE TITLE
jsonc with import maps 

### ISSUE THREAD

**Issue by Yaikava** [WICG/import-maps#264]
It would be nice to allow usage of .jsonc files for import maps so we can have comments in them.

I can see it being usefull in Deno for example.
https://github.com/denoland/deno/issues/12993#issue-1071304460

**Comment by ljharb** [comment]
Is there a facility in the browser to serialize and unserializability that format?

**Comment by Yaikava** [comment]
> Is there a facility in the browser to serialize and unserialize that format?

I have no idea about these stuff. Sorry

**Comment by domenic** [comment]
This is best done by compiling your JSONC into JSON.

**Comment by ooker777** [comment]
> Is there a facility in the browser to serialize and unserialize that format?

Not sure what you mean. Isn't that just a text string? Or do you mean a JSONC parser?

**Comment by ljharb** [comment]
Yes, 3 years ago, and still, I meant an actual JSONC parser.

**Comment by ooker777** [comment]
[@std/jsonc - JSR](https://jsr.io/@std/jsonc "@std/jsonc - JSR") works for browsers

**Comment by ljharb** [comment]
it's not built in, and

> Currently, this module only provides a means of parsing JSONC. JSONC serialization is not yet supported.
