### ISSUE TITLE
Default JSON filename for external tooling support.

### ISSUE THREAD

**Issue by GerryFerdinandus** [WICG/import-maps#266]
To autocomplete/verify with external tooling, a predefined filename must be used.
Example files name: [importmap.json, *-importmap.json]

An issue has been created in SchemaStore requesting this support. (issue [1](https://github.com/SchemaStore/schemastore/issues/957), [2](https://github.com/SchemaStore/schemastore/issues/2027))

The importmap specifications say nothing about a standard file name.
Or is this again the design specification to use a predefined filename?

**Comment by domenic** [comment]
Indeed, just like every other `<script>` element on the web (or `<link>` or `<img>` or...), you can use any filename you like!
