### ISSUE TITLE
In "the script’s type", the ’ is actually an unicode U+2019, instead of an ascii '

### ISSUE THREAD

**Issue by allstarschh** [WICG/import-maps#269]
https://wicg.github.io/import-maps/#ref-for-concept-script-type②

> the script’s type 

The ’ character is actually not an ascii, it's an U+2019 unicode character (RIGHT SINGLE QUOTATION MARK).

From The HTML spec, https://html.spec.whatwg.org/multipage/scripting.html#concept-script-type
> The script's type

It's using the ascii character, U+0027 APOSTROPHE

Same for the occurrences of element's
> element’s

(Notice this when I copy-paste the spec while editing a file whose encoding is ascii.)

**Comment by domenic** [comment]
Yeah, this is an artifact of the spec tooling we use, [Bikeshed](https://tabatkins.github.io/bikeshed/). There's not much we can do about it, sadly.

**Comment by ljharb** [comment]
What's wrong with that tho? Straight quotes aren't correct in prose anyways. I'd expect it to be `‘`
