### ISSUE TITLE
Typo in "A import map is a struct with two items:"

### ISSUE THREAD

**Issue by allstarschh** [WICG/import-maps#270]
https://wicg.github.io/import-maps/#definitions

> A import map is a struct with two items:​

Should be "An" import map

The following sentence spells correctly

> An empty [import map](https://wicg.github.io/import-maps/#import-map) is an import map

**Comment by domenic** [comment]
I believe this is fixed in https://github.com/whatwg/html/pull/8075. Please check. If so, I will close this when I remove all spec text from this repository and instead let HTML be the new source of truth.

**Comment by allstarschh** [comment]
Fixed in https://whatpr.org/html/8075/webappapis.html#import-map-processing-model

> Formally, **an** import map is a [struct](https://infra.spec.whatwg.org/#struct) with two [items](https://infra.spec.whatwg.org/#struct-item):
