### ISSUE TITLE
An empty map was create twice if "imports" or "scopes" exists

### ISSUE THREAD

**Issue by allstarschh** [WICG/import-maps#271]
https://wicg.github.io/import-maps/#parse-an-import-map-string

> 3. Let sortedAndNormalizedImports be an empty [map](https://infra.spec.whatwg.org/#ordered-map).

The first empty map is created here.

> 4.2. Set sortedAndNormalizedImports to the result of [sorting and normalizing a specifier map](https://wicg.github.io/import-maps/#sort-and-normalize-a-specifier-map) given parsed["imports"] and baseURL.

https://wicg.github.io/import-maps/#sort-and-normalize-a-specifier-map

> 1. Let normalized be an empty [map](https://infra.spec.whatwg.org/#ordered-map).

Here is the creation of the second empty map, in the sequence (when "imports" exists in import map)
The first empty map is redundant.

**Comment by guybedford** [comment]
I believe this redundancy is just an intentional way of handling the second branch and declaration together to avoid unnecessary verbosity. If you'd like to suggest an editorial edit to explicitly have the else branch that might be an option.
