### ISSUE TITLE
preparation-time document check should be done first at #register-an-import-map

### ISSUE THREAD

**Issue by hiroshige-g** [WICG/import-maps#276]
https://wicg.github.io/import-maps/#register-an-import-map

Currently `preparation-time document check` is done at Step 6, but to align with https://html.spec.whatwg.org/multipage/scripting.html#execute-the-script-block, the check should be before firing `error` event at Step 1.

(This is a quite low-priority issue found during Chromium implementation investigation for an unrelated non-import-map issue. I'll create a PR/impl fix when I have a spare bandwidth)

**Comment by domenic** [comment]
In my HTML spec PR I am directly using "execute a script element", so I hope this is fixed. Please check when I send that out for review.

**Comment by domenic** [comment]
I believe this is fixed in https://github.com/whatwg/html/pull/8075. Please check. If so, I will close this when I remove all spec text from this repository and instead let HTML be the new source of truth.
