### ISSUE TITLE
Throwing TypeError in resolve a module specifier?

### ISSUE THREAD

**Issue by allstarschh** [WICG/import-maps#277]
According to the import maps spec, resolve a module specifier will throw,
https://wicg.github.io/import-maps/#resolve-a-module-specifier, step 12

Also the callers will be updated as well, according to https://wicg.github.io/import-maps/#resolving-updates

But what about https://html.spec.whatwg.org/multipage/webappapis.html#validate-requested-module-specifiers
According to the HTML spec, the error should be propagated to the script's parse error
https://html.spec.whatwg.org/multipage/webappapis.html#concept-script-parse-error

and later it will be the error to rethrow object of the script.
https://html.spec.whatwg.org/multipage/webappapis.html#concept-script-error-to-rethrow

So in this case, should 'resolve a module specifier' still throw a TypeError if it has any?
Or it should return failure (like the original 'resolve a module specifier' does), and let script to propagate the error?

Note: V8's implementation is in 
[JSModuleScript::Create](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/script/js_module_script.cc;l=22;drc=5e62802ab420dc1743a1824ec4b537a730b2b24b)
[ModulatorImplBase::ResolveModuleSpecifier](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/script/modulator_impl_base.cc;l=107;drc=5e62802ab420dc1743a1824ec4b537a730b2b24b)
and
[ImportMap::Resolve](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/script/import_map.cc;l=391;drc=5e62802ab420dc1743a1824ec4b537a730b2b24b)

**Comment by domenic** [comment]
Yes, you're right that the propagation is a bit more complex for that caller. My plan was to convert it to catch the error and store it.

**Comment by domenic** [comment]
I believe this is fixed in https://github.com/whatwg/html/pull/8075. Please check. If so, I will close this when I remove all spec text from this repository and instead let HTML be the new source of truth.
