### ISSUE TITLE
TODO: write down the "resolve a module specifier" algorithm

### ISSUE THREAD

**Issue by domenic** [WICG/import-maps#6]
Preferably including a JS implementation, with at least rudimentary smoke tests.

I've got somewhat of a start on this, and will update this thread as I make progress. Alternately, help would be appreciated if someone else wants to do the work.

**Comment by justinfagnani** [comment]
Since we have a pretty good start, is it worth posting that in this issue or a PR for anyone who wants to take it from there?

**Comment by domenic** [comment]
I don't really trust what we have so far. And I'd like to develop in a much more test-first manner. So I'll avoid doing that for now.

Good discussions to make sure we take into account: #11, #13.

**Comment by domenic** [comment]
https://github.com/WICG/import-maps/commit/602333cc756e3fdecdbd06785155211cb0c9a671 added scopes. https://github.com/WICG/import-maps/commit/8e863b6151c2caacc1911e45e339e4d3db126e35 added built-in modules. The remaining work is to transcribe into a spec.
