### ISSUE TITLE
How to convert package-lock.json to import maps?

### ISSUE THREAD

**Issue by wmhilton** [WICG/import-maps#60]
This looks so cool! Are there any implementations of "package-lock.json -> package-name-map" translators yet? (Is that what I should be thinking of?)

(Edit by @domenic: at the time this comment was written the proposal was known as "package name maps". I've renamed the title to be "import maps", but left the body of subsequent comments alone. Sorry if that's confusing!)

**Comment by adrianhelvik** [comment]
Something like this should do it. You would use package.json and not package-lock.json.

    const fs = require('fs')

    const nameMap = fs
      .readdirSync(
        __dirname
        + '/node_modules'
      )
      .reduce((res, name) => {
        try {
          var package =  require(folder + '/package')
        } catch (e) {
          console.log(folder + ' had no package.json. Skipping...')
          return res
        }
        if (! package.module)
          return console.log(`"${name}" had no module filed. Skipping...`)
        res.packages[name] = {
          main: package.module
        }
        return res
      }, {
        path_prefix: '/node_modules',
        packages: {}
      })
      .filter(x => x)

    fs.writeFileSync(__dirname + '/package-map.json')

**Comment by tilgovi** [comment]
I would think you would want to package-lock.json unless you can guarantee that all dependencies are hoisted and totally flat.

**Comment by adrianhelvik** [comment]
Came to think of it. Do packages support a packages field? This would be crucial for node interop.

**Comment by wmhilton** [comment]
Exactly, package maps cannot be generated directly from the `"dependencies"` field of `package.json` because they only specify the first-order dependencies and even those are only by a semver range.

The equivalent to a package-name-map is a "lockfile" format, which is usually created during an actual install.

I suggested `package-lock.json` because it's the format used by `npm` and therefore ought to be a defacto standard. (The `npm` CLI automatically produces a `package-lock.json` after nearly any operation.) However, for maximum developer happiness and we'd want to be able to convert:

- `package-lock.json`
- `npm-shrinkwrap.json` (same format, different use case)
- `yarn.lock` (generated by `yarn`)
- `shrinkwrap.yaml` (generated by `pnpm`)

So that's at least 3 CLI tools that need to be built, I take it?

**Comment by tilgovi** [comment]
The `scopes` feature allows what you're looking for, but see also #5.

**Comment by daKmoR** [comment]
also Yarn Plug'n'Play: Implementation should be considered - It comes with it's own file/api

More Info here: https://github.com/yarnpkg/yarn/pull/6382

**Comment by daKmoR** [comment]
oh yeah, that looks promising... unfortunately not yet useful for web components.
I made a test with what is currently available

https://github.com/daKmoR/build-pnm-webcomponent-issue

I raised an issue there as well - hopefully, this will start a discussion about unique elements in a package name map. For anyone who is interested https://github.com/arcanis/build-pnm/issues/1.

**Comment by arcanis** [comment]
Thanks for the ping! I'm entering a plane but I'll share some points regarding the build-pnm utility later today!

In the meantime, can you details the reasons why webcomponents are expected to be flat, with a single version used accross an application? Since the pnm standard seems to support nested packages I wonder if there is a technical requirement I've missed in the spec 😃

**Comment by daKmoR** [comment]
@arcanis Actually, it's not a requirement of pnm - but first recap the main goal of pnm as far as I understood. 
**pnm should enable us to use bare modules within the browser without a build step**  
e.g. you can upload your full directory/source code as is and put it on a plain web/file server and it should work.

Keeping that in mind it means that we may have a lot of files on our server but we still want to ship as little a possible to our users/browser.

Naturally, that means we don't want to ship code doing the same thing multiple times. So using like 4 versions of for example `camelcase` in our application may be a bad idea regarding the file size - but it should still work. That is the reason why pnm supports multiple versions of a package. I would still find a warning, in that case, would be appropriate [1].

### Entering Webcomponents

For custom elements it's just not possibele to use different versions of the same element. It's a requirement of [CustomElementRegistry](https://html.spec.whatwg.org/multipage/custom-elements.html#customelementregistry). The relevant part is 
> If this CustomElementRegistry contains an entry with name name, then throw a "NotSupportedError" DOMException.

In good old english this means: "Each custom elements tag name needs to be unique within a browsers Window object".
Actually from a browsers point of view it's obvious there can only be one `<video>` tag.

Also a nice comment about it is https://github.com/domenic/package-name-maps/issues/5#issuecomment-374175653.


PS: there have been some workaround like creating unique custom element names by adding random strings but they definitely violate the idea to only ship as little as possible. 

---

[1]: This could be more than just a warning. You could even give some info on how to pin to certain versions that should be used. e.g. something like this,
> The package "camelcase" is used with the following versions 1.2.2, 1.3.0, 2.0.0, 2.0.9. You can run "pnm set-resolution camelcase 1.3.3 2.1.0" to only use the latest releases of each major version.

PS: Have a safe flight 👍

**Comment by wmhilton** [comment]
WebComponents is a significant change of topic from my original issue, which is asking what tools exist for creating `package-name-maps`. I would move that discussion to a new issue so as not to get them mixed up.

**Comment by domenic** [comment]
Looking forward to what people produce here. I'll note that the proposal has just changed radically (and been renamed), in ways that might make this more interesting.

**Comment by CarterLi** [comment]
I use following code to generate import maps from `yarn.lock`

```ts
import * as lockfile from '@yarnpkg/lockfile';
import { promises as fs } from 'fs';
import * as path from 'path';

export async function getImportMap(targetPath = __dirname) {
  const content = await fs.readFile(path.resolve(targetPath, 'yarn.lock'), 'utf-8');
  const json = lockfile.parse(content);

  return Object.assign({}, ...Object.keys(json.object)
    .map(x => x.slice(0, x.lastIndexOf('@')))
    .map(x => {
      try {
        return { [x]: '/' + path.relative(targetPath, require.resolve(x, { paths: [targetPath] })) };
      } catch {
        return { [x]: undefined };
      }
    }));
}
```

**Comment by CarterLi** [comment]
Generates import maps from `yarn.lock`

```js
import * as lockfile from '@yarnpkg/lockfile';
import { promises as fs } from 'fs';
import * as path from 'path';

export async function getImportMap(targetPath = __dirname) {
  const content = await fs.readFile(path.resolve(targetPath, 'yarn.lock'), 'utf-8');
  const json = lockfile.parse(content);

  return Object.assign({}, ...Object.keys(json.object)
    .map(x => x.slice(0, x.lastIndexOf('@')))
    .map(x => {
      try {
        const result = '/' + path.relative(targetPath, require.resolve(x, { paths: [targetPath] }));
        return { [x]: result, [x + '/']: path.dirname(result) + '/' };
      } catch {
        return { [x]: undefined } ;
      }
    }));
}
```

**Comment by ftaiolivista** [comment]
> Generates import maps from `yarn.lock`
> 
> ```ts
> import * as lockfile from '@yarnpkg/lockfile';
> import { promises as fs } from 'fs';
> import * as path from 'path';
> 
> export async function getImportMap(targetPath = __dirname) {
>   const content = await fs.readFile(path.resolve(targetPath, 'yarn.lock'), 'utf-8');
>   const json = lockfile.parse(content);
> 
>   return Object.assign({}, ...Object.keys(json.object)
>     .map(x => x.slice(0, x.lastIndexOf('@')))
>     .map(x => {
>       try {
>         const result = '/' + path.relative(targetPath, require.resolve(x, { paths: [targetPath] }));
>         return { [x]: result, [x + '/']: path.dirname(result) + '/' };
>       } catch {
>         return { [x]: undefined } ;
>       }
>     }));
> }
> ```
> 
> A working demo that uses import maps in browser with node_modules: https://github.com/CarterLi/web-esm/blob/master/index.ts#L27

Would be great to filter out development packages and generate map only for production ones.

**Comment by CarterLi** [comment]
> Would be great to filter out development packages and generate map only for production ones.

It's easy to filter out development packages themselves (by looking for package.json), but it's hard to filter out packages that dev packages depend on.

I dont know if yarn has an API to do so, or you will have to parse package.json in node_modules recursively

**Comment by ljharb** [comment]
package-lock already contains this information; anything with `dev: true` is something that's a dev dep, or a transitive dep of a dev dep that's not a transitive dep of a production dep (iow, safe to prune)

**Comment by dgreene1** [comment]
Would anyone be interested in turning the two snippets above into a CLI library so that we can have all the benefits of an open source package?

 (I.e. modularization, the package can be upgraded centrally, etc)

**Comment by adrianhelvik** [comment]
@dgreene1 Agree, but it can't really use require.resolve. Now it works relative to the file and not cwd.

**Comment by ljharb** [comment]
the resolve package allows a custom basedir; you could use that?

**Comment by daKmoR** [comment]
hey there 🤗 

we released a package that generates a `import-map.json` and/or injects it into your `index.html` based on your `yarn.lock`. It is on npm as [@import-maps/generate](https://www.npmjs.com/package/@import-maps/generate).

for now, it only supports `yarn.lock` files (including yarn workspaces for mono repos ✨ ).

There is currently only one mode we call "flat" which flattens all your production dependencies and asks on the command line if no version can be found to can satisfy all needs. If anyone wants to work on a "nested mode" with scopes join the party on [github](https://github.com/open-wc/open-wc/tree/master/packages/import-maps-generate).

if you just wanna try it out... just call `npx @import-maps/generate` in one of your projects.

This is still very early - so if you can give feedback it would be highly appreciated 🤗

**Comment by dmail** [comment]
I have done something capable to generate importMap for node_modules.
The npm package is called `@jsenv/node-module-import-map`.
If you want to test it you can run the following inside a folder with a package.json.

```shell
npm i --save-dev @jsenv/node-module-import-map
node -e "require('@jsenv/node-module-import-map').generateImportMapForProjectNodeModules({ projectPath: process.cwd() });"
```

It recursively reads package.json and tries to find dependencies on your filesystem using a custom node module resolution. The generated import map will scope import per node module.
It means if you depend on `lodash` importMap will contain the scope below:
```json
{
  "scopes": {
    "/node_modules/lodash/": {
      "/node_modules/lodash/": "/node_modules/lodash/",
      "/": "/node_modules/lodash/"
  }
}
```
It allows each module to have import starting with `/`.
So that inside `lodash` the following import

```js
import '/src/file.js'
```
would be remapped to `/node_modules/lodash/src/file.js` inside your project.

I give the link to the github repository in case you want to check source or unit tests for instance but the readme is empty for now: https://github.com/jsenv/jsenv-node-module-import-map.

**Comment by chase-moskal** [comment]
so cool to see everyone collaborating on new tooling for import maps :beers:

trying a different approach, i've been working on a command line tool

[**importly**](https://github.com/chase-moskal/importly) generates import maps from a funny-looking `importly.config` file, like this

```
📡 unpkg, jsdelivr
📦 mobx
📦 lit-html
📦 lit-element@^2.2.0
```

this importly config generates an import map that uses unpkg, but also jsdelivr is set as the fallback

```sh
importly < importly.config > dist/importmap.json
```

i'm currently using importly instead of npm, as a browser package manager

currently, importly doesn't integrate with npm's `package.json`/`package-lock.json` files, but that might still be a worthwhile enhancement for a hybrid workflow (importly during development, then bundling for production, perhaps)

also, i think importly could be made isomorphic, so perhaps during development it could run in-browser and completely cut out the build step, which might be rather slick :dark_sunglasses: 

i'm open to ideas and discussion, just open an issue on my repo if you're interested :)

cheers friends!
:wave: Chase

**Comment by domenic** [comment]
Just wanting to let people know that I have a pull request up at https://github.com/WICG/import-maps/pull/147 to consolidate all the tools people have been posting in this thread into the README. Also, I opened a new issue #146 to provide a general discussion space, in lieu of this issue + #108. So I'll close out this issue, but see you in #146! Thanks so much everyone for the cool stuff you've been building!
