### ISSUE TITLE
"However, service workers are not available on first load"

### ISSUE THREAD

**Issue by annevk** [WICG/import-maps#70]
Will this be true forever? If Origin Policy/Manifest somehow works well, I could imagine also preloading the service worker.

**Comment by domenic** [comment]
That is my current understanding talking to service worker engineers. I'd love to hear otherwise from them, if you've been talking to a different set of folks.

**Comment by annevk** [comment]
Given how far along Origin Policy/Manifest is (not that far), it seems a little premature to declare that this will never happen.

**Comment by domenic** [comment]
Ok. I'd be happy to continue this discussion if you can point to some concrete statements contrary to what I've heard.

**Comment by johntron** [comment]
Even if service workers become an option for the first page load, are there additional reasons for not using them? It might be useful to describe those as well. One that comes to mind is that service workers may not be available in some situations (private browsing?).

BTW - this proposal might solve an inevitable [problem when building microfrontends](https://medium.com/@_rchaves_/building-microfrontends-part-iii-public-path-problem-1ce823be24c9): loading assets from disparate servers in one browser runtime.

**Comment by Malvoz** [comment]
> Will this be true forever? If Origin Policy/Manifest somehow works well [...]

Alternatively, with [Early Hints](https://tools.ietf.org/html/draft-ietf-httpbis-early-hints) we could do:

```
HTTP/1.1 103 Early Hints
     Link: </sw.js>; rel=preload; as=script
```

And (?) if we kept [`rel=serviceworker`](https://github.com/w3c/ServiceWorker/issues/685#issuecomment-175295621):

```
HTTP/1.1 103 Early Hints
     Link: </sw.js>; rel=serviceworker; scope=/
```
