### ISSUE TITLE
Empty string scopes

### ISSUE THREAD

**Issue by guybedford** [WICG/import-maps#81]
@domenic mentions in https://github.com/domenic/import-maps/pull/67/files#r236505421 -

> Empty string scopes seem useful.

I wanted to just discuss this explicitly here - what sort of use cases does this enable that couldn't be done otherwise?

I take it the empty string scope corresponds to the current base URL, so that it provides a way to create package mappings that only apply within the current origin and path.

The concern is that this might not seem obvious / or might seem obscure.

Could a `.` scope not be a better way to describe this one? And while I'm suggesting this - would a "." scope be supported currently and would it merge with the empty string scope?

**Comment by domenic** [comment]
Technically there's a difference between `""` and `"."` / `"./"`:

- https://jsdom.github.io/whatwg-url/#url=&base=aHR0cHM6Ly9leGFtcGxlLmNvbS9mb28vYXBwLmh0bWw=
- https://jsdom.github.io/whatwg-url/#url=Lg==&base=aHR0cHM6Ly9leGFtcGxlLmNvbS9mb28vYXBwLmh0bWw=
- https://jsdom.github.io/whatwg-url/#url=Li8=&base=aHR0cHM6Ly9leGFtcGxlLmNvbS9mb28vYXBwLmh0bWw=

In particular, `""` would allow you to only change the behavior of module imports on a specific HTML file (or, theoretically, worker?), without having to restate the HTML file's name. I'm not sure this is an important use case, but I'm also not sure we should explicitly prohibit it.

**Comment by guybedford** [comment]
> In particular, "" would allow you to only change the behavior of module imports on a specific HTML file (or, theoretically, worker?), without having to restate the HTML file's name.

I see, it's a very specific use case then as if the import map were its own file, then this would be the file name of the import map itself. So this only really applies to workers and inline HTML maps.

My concern with the above is are we then giving inline maps extra features over maps in their own files?

**Comment by domenic** [comment]
> My concern with the above is are we then giving inline maps extra features over maps in their own files?

In some senses, yes, but this is true for all inline scripts (and I guess styles). Having your own URL be the same as the URL of the page is often a useful property for writing shorter code, and the same is true in import maps.
