### ISSUE TITLE
Trailing slash handling for URLs

### ISSUE THREAD

**Issue by guybedford** [WICG/import-maps#91]
Just reading through the implementation, all seems pretty good to me.

I'm still not 100% sold on the URL mapping, but it seems well-defined in the implementation :+1:

The only inconsistency seems to be that a trailing slash is supported for packages (`pkg/x` mapped by `pkg/`, but URLs don't seem to support the trailing slash - `/pkg/x` will not support a `/pkg/` map. This seems like a bit of an arbitrary restriction to me, where there could be use cases for mapping these.

Alternatively perhaps the map parser or resolver itself should explicitly throw / warn here as users won't necessarily understand immediately that there is a distinction between these.

**Comment by domenic** [comment]
This is a really interesting idea. I like the symmetry of supporting both. And I think it has a use case, namely polyfilling built-in packages that have multiple modules, e.g. something like

```json
{
  "imports": {
    "/node_modules/als-polyfill/": [
      "@std/async-local-storage/",
      "/node_modules/als-polyfill/"
    ]
  }
}
```

I realized that right now it's not obvious how trailing slashes combine with address arrays. I.e. given the following:

```json
{
  "imports": {
    "jquery/": [
      "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js",
      "/node_modules/jquery/dist/jquery.js"
    ]
  }
}
```

what does `"jquery/foo"` map to? I think the right answer is probably `"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js/foo"`? Or maybe just `"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.jsfoo"`, i.e. directly append the string?

I guess first we'd want to answer, given

```json
{
  "imports": {
    "moment/": "/node_modules/moment.js"
  }
}
```

what does `"moment/foo"` map to. Even that is not called out in any examples or tests so far, although I guess the reference implementation will have some behavior for it.

Action items:

- Write tests for what the current resolver does for the `"moment/foo"` case
- Discuss, and tweak the algorithm/tests if appropriate.
- Continue working on fallback resolution, and be consistent with the above.
- Once all that is in place, it should be pretty simple to extend to support URLs, with tests showing that it would be actually useful.

**Comment by jkrems** [comment]
What I did in `pkg-exports` was to say: Trailing slash needs to be consistent. This is restrictive because it doesn't allow mapping a trailing slashes to a single file (at least not nicely) but it makes the semantics very clear: If the mapping ends with a slash, additional stuff gets appended to both sides symmetrically. If it doesn't, nothing will ever be appended.

**Comment by domenic** [comment]
I'm a bit wary about baking in assumptions about peoples' URL structures into the import map infrastructure (i.e., right now paths are generally treated opaquely). But that seems simplest, and probably the right thing to do since it's conservative and can be expanded later.

**Comment by guybedford** [comment]
Just saw this one now - perhaps https://github.com/domenic/import-maps/issues/93 answers this?
