### ISSUE TITLE
Consider support module identifiers as a whitelist

### ISSUE THREAD

**Issue by koto** [WICG/import-maps#99]
Is is possible to optionally make the module map a whitelist of module identifiers that can be imported? For most applications it should be possible to generate the modules that the application uses at deployment time, allowing the module map to serve like a next-generation CSP `script-src` directive, but tailored to modules. That seems like a useful property.

**Comment by domenic** [comment]
I think that's out of scope for this proposal, and instead makes more sense as part of CSP's script-src. Safelisting really should be done at the URL level, not at this one-level-removed abstraction.

**Comment by guybedford** [comment]
Dynamic `import` is clearly a security vulnerability, and import maps are the way to control its resolution so this argument definitely makes a lot of sense.

For example, if every scope of the import map was restricted to only be allowed to load relative URLs from within its own scope, and every other URL had to be explicitly determined in the import map we would get some amazing security properties.

But our entire development of the web is based on the concept of security as an afterthought, and the processes are certainly not in place to change that here, so this certainly won't be viable.

**Comment by koto** [comment]
> * If URL whitelists are not useful, why would module specifier whitelists be good, when module specifiers map directly to URLs?

Because I think they offer a more interesting (from a security perspective) abstraction for the modern applications - instead of a flat list of URLs, a tree that describes the application dependencies, together with a way of limiting certain capabilities to certain modules. It seems useful to treat it as some sort of application manifest, and then enforcing that the application at runtime adheres to it provides security benefits. In the current form of the proposal, this seems like quite close to be able to achieve this. Simply (if the application opts-in) deny loading modules that are not on the import map. 

> * The fact that there's no way to pash a hash or nonce for module imports is a separate discussion, not related to this issue, or indeed to the import maps proposal.

Yes, I agree, sorry for conflating those two. Nonces are, in general, not the way to go anyway for modules, but it feels like hashes might (though, understandably, URL => hash map can also just be specified elsewhere; this just seems like a nice place for it as well).

**Comment by domenic** [comment]
OK. I suggest instead you use a manifest format that works for all URLs and resources, not just modules that need a specifier alias.
